
platform :ios, '8.0'
# use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target 'PlaneLive' do
    
    pod 'AFNetworking'
    
    pod 'Bugly'
    pod 'DACircularProgress'
    
    pod 'FMDB'
    pod 'FMDB/SQLCipher'
    
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'Masonry'
    
    pod 'SDWebImage'
    pod 'SECoreTextView'
    pod 'SDCycleScrollView'
    pod 'TYAttributedLabel'
    pod 'TZImagePickerController'
    
    pod 'ZPushKit'
    pod 'ZPlayerKit'
    # 高德地图
    pod 'AMap3DMap-NO-IDFA'
    pod 'AMapLocation-NO-IDFA'
    
    pod 'UMengAnalytics-NO-IDFA'
    
    # 主模块(必须)
    pod 'mob_sharesdk'
    pod 'mob_sharesdk/ShareSDKUI'
    pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
    pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
    pod 'mob_sharesdk/ShareSDKPlatforms/Evernote'
    pod 'mob_sharesdk/ShareSDKConfigurationFile'
    pod 'mob_sharesdk/ShareSDKExtension'
    
    pod 'Zhugeio'
end

