//
//  EventKeyManager.h
//  PlaneCircle
//
//  Created by Daniel on 7/14/16.
//  Copyright © 2016 WT. All rights reserved.
//

#import <Foundation/Foundation.h>


/**************UMeng事件统计**************/


#define kObjectId @"ObjectId"
#define kObjectTitle @"ObjectTitle"
#define kObjectType @"ObjectType"
#define kObjectPrice @"ObjectPrice"
#define kObjectUser @"ObjectUser"


#define kHomepage_Search @"Homepage_Search"
#define kHomepage_Search_EriesCourse @"Homepage_Search_EriesCourse"
#define kHomepage_Search_Training @"Homepage_Search_Training"
#define kHomepage_Search_ListItem @"Homepage_Search_ListItem"
#define kHomepage_Search_EriesCourse_ListItem @"Homepage_Search_EriesCourse_ListItem"
#define kHomepage_Search_Training_ListItem @"Homepage_Search_Training_ListItem"
#define kHomepage_Banner @"Homepage_Banner"
#define kHomepage_Practice @"Homepage_Practice"
#define kHomepage_PopularTraining @"Homepage_PopularTraining"
#define kHomepage_SeriesCourse @"Homepage_SeriesCourse"
#define kHomepage_PracticeAll @"Homepage_PracticeAll"
#define kHomepage_ProfessionalOrganizationsAll @"Homepage_ProfessionalOrganizationsAll"
#define kHomepage_PopularTrainingAll @"Homepage_PopularTrainingAll"
#define kHomepage_SeriesCourseAll @"Homepage_SeriesCourseAll"
#define kHomepage_BoutiqueQusetionAll @"Homepage_BoutiqueQusetionAll"
#define kHomepage_ProfessionalOrganizations_ListItem @"Homepage_ProfessionalOrganizations_ListItem"
#define kHomepage_Practice_ListItem @"Homepage_Practice_ListItem"
#define kHomepageSeries_Lessons_ListItem @"HomepageSeries_Lessons_ListItem"
#define kHomepageSeries_Training_ListItem @"HomepageSeries_Training_ListItem"
#define kHomepageSeries_BoutiqueQusetion_ListItem @"HomepageSeries_BoutiqueQusetion_ListItem"
#define kPractice_Detail @"Practice_Detail"
#define kPractice_Detail_Play @"Practice_Detail_Play"
#define kPractice_Detail_Download @"Practice_Detail_Download"
#define kPractice_Detail_Deward @"Practice_Detail_Deward"
#define kPractice_Detail_PPT @"Practice_Detail_PPT"
#define kPractice_Detail_Praise @"Practice_Detail_Praise"
#define kPractice_Detail_Collection @"Practice_Detail_Collection"
#define kPractice_Detail_AnsweringQuestion @"Practice_Detail_AnsweringQuestion"
#define kPractice_Detail_Courseware @"Practice_Detail_Courseware"
#define kPractice_Detail_Suspend @"Practice_Detail_Suspend"
#define kPractice_Detail_Previous @"Practice_Detail_Previous"
#define kPractice_Detail_Next @"Practice_Detail_Next"
#define kPractice_Detail_Play @"Practice_Detail_Play"
#define kPractice_Detail_List_PlayTime @"Practice_Detail_List_PlayTime"
#define kPractice_Detail_Playlists @"Practice_Detail_Playlists"
#define kPractice_Detail_Share @"Practice_Detail_Share"
#define kPractice_Detail_Share_WeChatCircle @"Practice_Detail_Share_WeChatCircle"
#define kPractice_Detail_Share_Wechat @"Practice_Detail_Share_Wechat"
#define kPractice_PayDetails @"Practice_PayDetails"
#define kPractice_PayDetails_Pay @"Practice_PayDetails_Pay"
#define kPractice_PayDetails_Pay_Balancepay @"Practice_PayDetails_Pay_Balancepay"
#define kPractice_PayDetails_Join @"Practice_PayDetails_Join"
#define kPractice_PayDetails_Join_ShoppingCart @"Practice_PayDetails_Join_ShoppingCart"
#define kPractice_PayDetails_Join_ShoppingCart_Settlement @"Practice_PayDetails_Join_ShoppingCart_Settlement"
#define kPractice_PayDetails_Join_ShoppingCart_Settlement_Balancepay @"Practice_PayDetails_Join_ShoppingCart_Settlement_Balancepay"
#define kEriesCourse_Detail @"EriesCourse_Detail"
#define kEriesCourse_Detail_AcademicProbation @"EriesCourse_Detail_AcademicProbation"
#define kEriesCourse_Detail_Pay @"EriesCourse_Detail_Pay"
#define kEriesCourse_Detail_Pay_Balancepay @"EriesCourse_Detail_Pay_Balancepay"
#define kEriesCourse_ListItem @"EriesCourse_ListItem"
#define kEriesCourse_Detail_Message @"EriesCourse_Detail_Message"
#define kEriesCourse_Detail_Play @"EriesCourse_Detail_Play"
#define kEriesCourse_Detail_Download @"EriesCourse_Detail_Download"
#define kEriesCourse_Detail_Praise @"EriesCourse_Detail_Praise"
#define kEriesCourse_Detail_Collection @"EriesCourse_Detail_Collection"
#define kEriesCourse_Detail_List_PlayTime @"EriesCourse_Detail_List_PlayTime"
#define kEriesCourse_Detail_Deward @"EriesCourse_Detail_Deward"
#define kEriesCourse_Detail_Writemessages @"EriesCourse_Detail_Writemessages"
#define kEriesCourse_Detail_Share @"EriesCourse_Detail_Share"
#define kEriesCourse_Detail_Share_WechatCircle @"EriesCourse_Detail_Share_WechatCircle"
#define kEriesCourse_Detail_Share_Wechat @"EriesCourse_Detail_Share_Wechat"
#define kTraining_Detail @"Training_Detail"
#define kTraining_Detail_AcademicProbation @"Training_Detail_AcademicProbation"
#define kTraining_Detail_Deward @"Training_Detail_Deward"
#define kTraining_Detail_Play @"Training_Detail_Play"
#define kTraining_Detail_List_PlayTime @"Training_Detail_List_PlayTime"
#define kTraining_Detail_Pay @"Training_Detail_Pay"
#define kTraining_Detail_Download @"Training_Detail_Download"
#define kTraining_Detail_Collection @"Training_Detail_Collection"
#define kTraining_Detail_Praise @"Training_Detail_Praise"
#define kTraining_Detail_Message @"Training_Detail_Message"
#define kTraining_Detail_Pay_Balancepay @"Training_Detail_Pay_Balancepay"
#define kTraining_ListItem @"Training_ListItem"
#define kTraining_Detail_Share @"Training_Detail_Share"
#define kTraining_Detail_Share_WechatCircle @"Training_Detail_Share_WechatCircle"
#define kTraining_Detail_Share_Wechat @"Training_Detail_Share_Wechat"
#define kPurchase_Practice @"Purchase_Practice"
#define kPurchase_Practice_ListItem @"Purchase_Practice_ListItem"
#define kPurchase_EriesCourse @"Purchase_EriesCourse"
#define kPurchase_EriesCourse_ListItem @"Purchase_EriesCourse_ListItem"
#define kPurchase_Training @"Purchase_Training"
#define kPurchase_Training_ListItem @"Purchase_Training_ListItem"
#define kDiscovery_Classification_List_Item @"Discovery_Classification_List_Item"
#define kCircle_Dynamic @"Circle_Dynamic"
#define kCircle_Topic @"Circle_Topic"
#define kCircle_Search @"Circle_Search"
#define kCircle_Question @"Circle_Question"
#define kCircle_Recommend @"Circle_Recommend"
#define kCircle_New @"Circle_New"
#define kUser_Edit @"User_Edit"
#define kUser_ShoppingCart @"User_ShoppingCart"
#define kUser_ExpenseCalendar @"User_ExpenseCalendar"
#define kUser_Purchase @"User_Purchase"
#define kUser_MYCollection @"User_MYCollection"
#define kUser_MYAtt @"User_MYAtt"
#define kUser_Download @"User_Download"
#define kUser_Message @"User_Message"
#define kUser_MYWaitAnswer @"User_MYWaitAnswer"
#define kUser_NoticeCenter @"User_NoticeCenter"
#define kUser_MYQuestion @"User_MYQuestion"
#define kUser_MYAnswer @"User_MYAnswer"
#define kUser_MYComment @"User_MYComment"
#define kUser_MYFans @"User_MYFans"
#define kUser_FeebBack @"User_FeebBack"
#define kUser_Customer @"User_Customer"
#define kUser_Balance @"User_Balance"
#define kUser_Balance_Recharge @"User_Balance_Recharge"
#define kUser_Setting @"User_Setting"
#define kUser_Setting_UpdatePWD @"User_Setting_UpdatePWD"
#define kUser_Setting_Blacklist @"User_Setting_Blacklist"
#define kUser_Setting_Clearcache @"User_Setting_Clearcache"
#define kUser_Setting_Clearcache_Determine @"User_Setting_Clearcache_Determine"
#define kUser_Setting_Clearcache_Cancel @"User_Setting_Clearcache_Cancel"
#define kUser_Setting_FontSize @"User_Setting_FontSize"
#define kUser_Setting_Push @"User_Setting_Push"
#define kUser_Setting_BUGOUT @"User_Setting_BUGOUT"
#define kUser_Setting_Score @"User_Setting_Score"
#define kUser_Setting_About @"User_Setting_About"
#define kUser_Setting_Exit @"User_Setting_Exit"
#define kCircle_Topic_ListItem @"Circle_Topic_ListItem"
#define kCircle_Topic_ListItem_Practice @"Circle_Topic_ListItem_Practice"
#define kCircle_Topic_ListItem_Practice_ListItem @"Circle_Topic_ListItem_Practice_ListItem"
#define kUser_Edit_Photo @"User_Edit_Photo"
#define kUser_Edit_NickName @"User_Edit_NickName"
#define kUser_Edit_Signature @"User_Edit_Signature"
#define kUser_Edit_Gender @"User_Edit_Gender"
#define kUser_Edit_Birthday @"User_Edit_Birthday"
#define kUser_Edit_Education @"User_Edit_Education"
#define kUser_Edit_Industry @"User_Edit_Industry"
#define kUser_Edit_EntryDate @"User_Edit_EntryDate"
#define kUser_Edit_Company @"User_Edit_Company"
#define kUser_Edit_Address @"User_Edit_Address"


/**************诸葛IO事件统计**************/


#define kZhugeIOHomeSearchPracticeKey @"搜索微课"
#define kZhugeIOHomeSearchTrainCourseKey @"搜索培训课"
#define kZhugeIOHomeSearchSeriesCourseKey @"搜索系列课"

#define kZhugeIOHomeKeywordsKey @"关键字"

#define kZhugeIOPayStartKey @"开始支付"
#define kZhugeIOPaySuccessKey @"支付成功"
#define kZhugeIOPayFailKey @"支付失败"

#define kZhugeIORechargeSuccessKey @"充值成功"
#define kZhugeIORechargeFailKey @"充值失败"

#define kZhugeIOPayTypeKey @"支付方式"
#define kZhugeIOPayMoneyKey @"支付金额"
#define kZhugeIOOrderNumberKey @"订单编号"
#define kZhugeIOGoodsNameKey @"商品名称"

#define kZhugeIORegisterSuccessKey @"注册成功"
#define kZhugeIORegisterFailKey @"注册失败"
#define kZhugeIOUserAccountKey @"用户账号"
#define kZhugeIOFailCauseKey @"失败原因"

#define kZhugeIOOnlineLecturesKey @"在线听课"

#define kZhugeIOCourseNameKey @"课程名称"
#define kZhugeIOCourseTypeKey @"课程分类"
#define kZhugeIOLecturerNameKey @"讲师"
#define kZhugeIOLecturerTitleKey @"讲师头衔"
#define kZhugeIOPriceKey @"价格"
#define kZhugeIOIsFreeKey @"是否免费"

#define kZhugeIOPageHomeKey @"首页"
#define kZhugeIOPageHomePracticeKey @"首页->微课"
#define kZhugeIOPageHomeSeriesKey @"首页->系列课"
#define kZhugeIOPageHomeTrainingKey @"首页->培训课"

#define kZhugeIOPagePurchasedKey @"已购"
#define kZhugeIOPagePurchasedPracticeKey @"已购->微课"
#define kZhugeIOPagePurchasedSeriesKey @"已购->系列课"
#define kZhugeIOPagePurchasedTrainingKey @"已购->培训课"

#define kZhugeIOPageUserKey @"我的"
#define kZhugeIOPageUserEditUserCenterKey @"我的->编辑个人资料"
#define kZhugeIOPageUserShoppingCartKey @"我的->购物车"
#define kZhugeIOPageUserBalanceKey @"我的->余额"
#define kZhugeIOPageUserMessageCenterKey @"我的->消息中心"

#define kZhugeIOPageChargeCourseDetailKey @"收费课程详情"
#define kZhugeIOPagePlayKey @"播放页面"
#define kZhugeIOPageCoursewareKey @"课件"

#define kZhugeIOTypeKey @"类型"
#define kZhugeIONormalKey @"正常"

#define kZhugeIOUserIdKey @"用户ID"
#define kZhugeIOUserTypeKey @"用户类型"
#define kZhugeIOUserTypePhoneKey @"手机用户"
#define kZhugeIOUserTypeWeChatKey @"微信用户"
#define kZhugeIOUserTypeQQKey @"QQ用户"

#define kZhugeIOCountryKey @"国家"
#define kZhugeIOProvinceKey @"省份"
#define kZhugeIOCityKey @"城市"
#define kZhugeIODistrictKey @"区域"
#define kZhugeIODeviceTypeKey @"设备型号"

#define kZhugeIOUserLoginSuccessKey @"用户登录"
#define kZhugeIOUserLoginFailKey @"登录失败"
