
target "PlaneLive" do
    
    pod "AFNetworking"
    pod "FMDB"
    pod "MBProgressHUD"
    pod "MJExtension"
    pod "MJRefresh"
    pod "SDWebImage"
    pod "pop"
    pod "SECoreTextView"
    pod "SDCycleScrollView"
    pod "TYAttributedLabel"
    pod "DACircularProgress"
    pod "FMDB/SQLCipher"
    pod "IDMPhotoBrowser"
    pod "TZImagePickerController"
    pod "YZHeaderScaleImage"
    pod "SDCycleScrollView"
    pod "UMengAnalytics-NO-IDFA"
    pod "MOBFoundation"
    pod "ShareSDK3"
    pod "ShareSDK3/ShareSDKUI"
    pod "ShareSDK3/ShareSDKPlatforms/QQ"
    pod "ShareSDK3/ShareSDKPlatforms/WeChat"
    pod "ShareSDK3/ShareSDKPlatforms/Evernote"
    pod "ShareSDK3/ShareSDKConfigurationFile"
    pod "ShareSDK3/ShareSDKExtension"
    
end

