

target "PlaneLive" do
    
    pod "AFNetworking"
    pod "FMDB"
    pod "MBProgressHUD"
    pod "MJExtension"
    pod "MJRefresh"
    pod "SDWebImage"
    pod "pop"
    pod "SECoreTextView"
    pod "TYAttributedLabel"
    pod "DACircularProgress"
    pod "FMDB/SQLCipher"
    pod "IDMPhotoBrowser"
    pod "UMengAnalytics-NO-IDFA"
    pod "QBImagePickerController"
    
end
