
platform :ios, '8.0'
# use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target 'PlaneLive' do
    
    pod 'AFNetworking'
    
    pod 'Bugly'
    pod 'DACircularProgress'
    
    pod 'FMDB'
    pod 'FMDB/SQLCipher'
    
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'Masonry'
    
    pod 'SDWebImage'
    pod 'SECoreTextView'
    pod 'SDCycleScrollView'
    pod 'TYAttributedLabel'
    pod 'TZImagePickerController'
    
    # 高德地图
    #pod 'AMap3DMap-NO-IDFA'
    pod 'AMapLocation-NO-IDFA'
    
    # UMeng
    pod 'UMCPush'
    pod 'UMCCommon'
    pod 'UMCAnalytics'
    pod 'UMCSecurityPlugins'
    
    # ShareSDK
    pod 'mob_sharesdk'
    pod 'mob_sharesdk/ShareSDKUI'
    pod 'mob_sharesdk/ShareSDKExtension'
    pod 'mob_sharesdk/ShareSDKConfigFile'
    pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
    pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
    
    pod 'Zhugeio'
    pod 'ZPlayerKit'
end

